package com.huagui.common.base;

/**
 * Created by lsk on 2017/4/23.
 */
public enum ServiceName {
    /**
     *
     */
    ALL("ALL"),
    BEAM_YARD_SERVICE("BEAM_YARD_SERVICE"),
    BIM_MANAGE_SERVICE("BIM_MANAGE_SERVICE"),
    CITYMAKER_SERVICE("CITYMAKER_SERVICE"),
    COMLIB_SERVICE("COMLIB_SERVICE"),
    HOMEPAGE_SERVICE("HOMEPAGE_SERVICE"),
    METRO_PROJECT_SERVICE("METRO_PROJECT_SERVICE"),
    NEW_METRO_PROJECT_SERVICE("NEW_METRO_PROJECT_SERVICE"),
    OA_SERVICE("OA_SERVICE"),
    OTHER_SERVICE("OTHER_SERVICE"),
    SURVEY_SERVICE("SURVEY_SERVICE"),
    PROGRESS_PLAN_SERVICE("PROGRESS-PLAN-SERVICE"),
    INVEST_MANAGEMENT_SERVICE("INVEST-MANAGEMENT-SERVICE"),
    INVEST_SERVICE("INVEST-SERVICE"),
    ASSET_SERVICE("ASSET-SERVICE"),
    //TODO remove
    PROCESS_PLAN_SERVICE("PROCESS-PLAN-SERVICE"),
    CLOUD_SERVICE("CLOUD-SERVICE"),
    USER_SERVICE("USER_SERVICE"),
    EQUIP_SERVICE("EQUIP_SERVICE");

    private String value;

    ServiceName(String value) {
        this.value = value;
    }
}
