package com.huagui.common.base;

/**
 * Created by tony on 2017/8/26.
 */
public enum ServiceExchange {
    METRO_PROJECT_EXCHANGE, USER_SERVICE_EXCHANGE, COMLIB_SERVICE_EXCHANGE, BIM_MANAGE_EXCHANGE, NEWOA_SERVICE_EXCHANGE,
    CLOUD_SERVICE_EXCHANGE,PROGRESS_PLAN_EXCHANGE,ASSET_SERVICE_EXCHANGE
}
