spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true #启动重试机制
    kubernetes:
      enabled: true
      config:
        name: ${spring.application.name}
        namespace: ${NAMESPACE:dev}
  redis:
    cluster:
      nodes: ${REDIS_CLUSTER_NODES:redis-cluster-0:6379,redis-cluster-1:6379,redis-cluster-2:6379}
  datasource:
    dynamic:
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: ${MYSQL_USERNAME}
          password: ${MYSQL_PASSWORD}
        slave:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: ${MYSQL_USERNAME}
          password: ${MYSQL_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_POINT:192.168.1.207:9092}
s3:
  accessKey: ${ACCESS_KEY:admin}
  secretKey: ${SECRET_KEY:admin123}
  bucket: ${BUCKET:bim-ops-bucket}
  endpoint: ${END_POINT:https://minio-test.hjbim.com}
